In [53]:
import numpy as np
import tensorflow as tf
import keras
from keras import layers
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from keras.utils import to_categorical

In [54]:
sentences=[
    "I love my dog",
    "I love my cat",
    "You love my dog",
    "I like to learn ML",
    "I enjoy learning new things",
    "At can perform many task",
    "Artificial Intelligence is the future",
    "Machine Learning is the future",
    "Deep Learning is the future"


]

In [55]:
my_tokenizer=Tokenizer()
my_tokenizer.fit_on_texts(sentences)

In [56]:
my_tokenizer.word_index

{'i': 1,
 'love': 2,
 'my': 3,
 'learning': 4,
 'is': 5,
 'the': 6,
 'future': 7,
 'dog': 8,
 'cat': 9,
 'you': 10,
 'like': 11,
 'to': 12,
 'learn': 13,
 'ml': 14,
 'enjoy': 15,
 'new': 16,
 'things': 17,
 'at': 18,
 'can': 19,
 'perform': 20,
 'many': 21,
 'task': 22,
 'artificial': 23,
 'intelligence': 24,
 'machine': 25,
 'deep': 26}

In [57]:
total_words=len(my_tokenizer.word_index)+1
total_words

27

In [58]:
input_sequences=[]
for i in sentences:
  token_list=my_tokenizer.texts_to_sequences([i])[0]
  for j in range(1,len(token_list)):
    n_gram_sequence=token_list[:j+1]
    input_sequences.append(n_gram_sequence)

In [59]:
input_sequences

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 8],
 [1, 2],
 [1, 2, 3],
 [1, 2, 3, 9],
 [10, 2],
 [10, 2, 3],
 [10, 2, 3, 8],
 [1, 11],
 [1, 11, 12],
 [1, 11, 12, 13],
 [1, 11, 12, 13, 14],
 [1, 15],
 [1, 15, 4],
 [1, 15, 4, 16],
 [1, 15, 4, 16, 17],
 [18, 19],
 [18, 19, 20],
 [18, 19, 20, 21],
 [18, 19, 20, 21, 22],
 [23, 24],
 [23, 24, 5],
 [23, 24, 5, 6],
 [23, 24, 5, 6, 7],
 [25, 4],
 [25, 4, 5],
 [25, 4, 5, 6],
 [25, 4, 5, 6, 7],
 [26, 4],
 [26, 4, 5],
 [26, 4, 5, 6],
 [26, 4, 5, 6, 7]]

In [60]:
max_sequence_len=max([len(x) for x in input_sequences])
print(max_sequence_len)
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

5


In [61]:
input_sequences

array([[ 0,  0,  0,  1,  2],
       [ 0,  0,  1,  2,  3],
       [ 0,  1,  2,  3,  8],
       [ 0,  0,  0,  1,  2],
       [ 0,  0,  1,  2,  3],
       [ 0,  1,  2,  3,  9],
       [ 0,  0,  0, 10,  2],
       [ 0,  0, 10,  2,  3],
       [ 0, 10,  2,  3,  8],
       [ 0,  0,  0,  1, 11],
       [ 0,  0,  1, 11, 12],
       [ 0,  1, 11, 12, 13],
       [ 1, 11, 12, 13, 14],
       [ 0,  0,  0,  1, 15],
       [ 0,  0,  1, 15,  4],
       [ 0,  1, 15,  4, 16],
       [ 1, 15,  4, 16, 17],
       [ 0,  0,  0, 18, 19],
       [ 0,  0, 18, 19, 20],
       [ 0, 18, 19, 20, 21],
       [18, 19, 20, 21, 22],
       [ 0,  0,  0, 23, 24],
       [ 0,  0, 23, 24,  5],
       [ 0, 23, 24,  5,  6],
       [23, 24,  5,  6,  7],
       [ 0,  0,  0, 25,  4],
       [ 0,  0, 25,  4,  5],
       [ 0, 25,  4,  5,  6],
       [25,  4,  5,  6,  7],
       [ 0,  0,  0, 26,  4],
       [ 0,  0, 26,  4,  5],
       [ 0, 26,  4,  5,  6],
       [26,  4,  5,  6,  7]], dtype=int32)

In [62]:
X_train=input_sequences[:,:-1]
label=input_sequences[:,-1]

In [63]:
print(X_train[2])
print(label[2])

[0 1 2 3]
8


In [64]:
output_c=to_categorical(label,num_classes=total_words)
output_c[2]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
RNN=keras.Sequential([
    layers.Embedding(total_words,100,input_length=max_sequence_len-1),
    layers.SimpleRNN(150),
    layers.Dense(total_words,activation='softmax')

])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [66]:
RNN.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [67]:
RNN.fit(X_train,output_c,epochs=100,verbose=1)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - accuracy: 0.0306 - loss: 3.3006
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2143 - loss: 3.2015
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4489 - loss: 3.1304
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.3368 - loss: 3.0606
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.2756 - loss: 2.9881
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.2756 - loss: 2.9076
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.2756 - loss: 2.8393
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.2756 - loss: 2.7666
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2756 - loss: 2.6879
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.2756 - loss: 2.6051
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.3980 - loss: 2.5376
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.3980 - lo

In [69]:
seed_text = __builtins__.input("Enter the text: ")
token_list = my_tokenizer.texts_to_sequences([seed_text])[0]
token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
predicted = RNN.predict(token_list)
predicted


Enter the text: I love
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step


array([[8.3781558e-04, 9.6694659e-04, 4.8793978e-03, 8.1641936e-01,
        3.8342118e-02, 1.9585199e-03, 8.2390971e-04, 2.8062891e-03,
        1.1661740e-03, 1.2147240e-03, 6.0689216e-04, 4.2542201e-03,
        8.7108172e-02, 2.2401989e-03, 6.1490748e-04, 2.8437236e-03,
        1.7906819e-03, 3.0305059e-04, 7.0294185e-04, 8.1858439e-03,
        1.2212462e-02, 1.3850851e-03, 9.1117725e-04, 8.4962416e-04,
        4.3388386e-03, 1.1415532e-03, 1.0952312e-03]], dtype=float32)

In [70]:
predicted=np.argmax(predicted,axis=1)
print(predicted)

[3]


In [71]:
predicted_word=""
for word,index in my_tokenizer.word_index.items():
  if index==predicted:
    predicted_word=word
    break
print(f"The next word is:{predicted_word}")

The next word is:my
